# Generated by Django 3.1.4 on 2021-01-31 23:36

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Raspberry Pi', max_length=20)),
                ('sid', models.CharField(default='None', max_length=15)),
                ('color', colorful.fields.RGBColorField(default='#FF0000')),
                ('desc', models.TextField(default='Data channel source')),
            ],
        ),
        migrations.CreateModel(
            name='StationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(default='None', max_length=15)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor_type', models.CharField(default='unknown', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Station Data',
            },
        ),
    ]
