# Generated by Django 3.1.4 on 2021-01-31 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pivarium', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name_plural': 'Sensors'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name_plural': 'Stations'},
        ),
    ]
