# Generated by Django 3.1.4 on 2021-02-01 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivarium', '0002_auto_20210131_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationdata',
            name='station',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pivarium.station'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.CharField(max_length=5),
        ),
    ]
