# Generated by Django 3.1.4 on 2021-02-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivarium', '0003_auto_20210131_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_time', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name_plural': 'Client Settings',
            },
        ),
    ]
